// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzuFfPKm_wzaB8lQ79X34YgD_WuD2xihI',
    appId: '1:421161035067:web:d1a6bd1b8d49498608831e',
    messagingSenderId: '421161035067',
    projectId: 'gemini-hackathon-51fbd',
    authDomain: 'gemini-hackathon-51fbd.firebaseapp.com',
    databaseURL: 'https://gemini-hackathon-51fbd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gemini-hackathon-51fbd.appspot.com',
    measurementId: 'G-XMF9EZY74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB248beoP8l1qjRFan5qGIm9FlW3gyRhzw',
    appId: '1:421161035067:android:057dc99b441a995408831e',
    messagingSenderId: '421161035067',
    projectId: 'gemini-hackathon-51fbd',
    databaseURL: 'https://gemini-hackathon-51fbd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gemini-hackathon-51fbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhkxNg0WW9-956EJPveJyZME7IN8za7g',
    appId: '1:421161035067:ios:29e9d96a04e3bb5008831e',
    messagingSenderId: '421161035067',
    projectId: 'gemini-hackathon-51fbd',
    databaseURL: 'https://gemini-hackathon-51fbd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gemini-hackathon-51fbd.appspot.com',
    iosBundleId: 'com.example.geminiHackathon',
  );

}